### ISSUE TITLE
Mateusz Kuzak needs to be added to the list of authors

### ISSUE THREAD

**Issue by liekelotte** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#10]
In the [author file](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/AUTHORS), Mateusz Kuzak is not mentioned, while he did contribute to the lesson. Can we add his name and email address to the list of authors?

**Comment by mkuzak** [comment]
@liekelotte I can fix that.
