### ISSUE TITLE
The link to lessons about R is not working

### ISSUE THREAD

**Issue by liekelotte** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#12]
Something seems to be wrong with the [link to lessons about R](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/#prerequisites) in the prerequisites. We should update the [index.md file](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/index.md) so that the link redirects to the right place

**Comment by ASarafoglou** [comment]
I will solve this issue!
