### ISSUE TITLE
Correct URL to CRAN in Accessing packages episode

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#14]
The URL of CRAN in [Accessing Packages episode](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/tree/main/episodes) is broken. It is `https://cran.r_project.org/` and should be 'https://cran.r-project.org/'. The fix needs to be made in the respective file [/episodes/accessing.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/accessing.Rmd) the broken URL is on [line 30](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/accessing.Rmd#L30).

Se the [Accessing packages episode](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/accessing.html) of the lesson.

**Comment by LizGuzRam** [comment]
I will work on this issue and will try to tag @eyesofbambi
