### ISSUE TITLE
Grammar improvement in the Introduction.

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#15]
Change `amount of people` to `number of people` in the Introduction. The phrase is on [line 50](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/introduction.Rmd#L50C71-L50C71) of the [episodes/introduction.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/introduction.Rmd#L50C71-L50C71)

See the [Introduction episode](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/introduction.html) of the lesson.

**Comment by himbosurf** [comment]
I will change this...
