### ISSUE TITLE
Correct the exercise timing in Getting started episode

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#16]
The exercises in Getting started episode take longer than initially expected. Change 10 to 15 in the header on [line 4](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/getting_started.Rmd#L4) of [episodes/getting_started.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/getting_started.Rmd#L4)

See the [Getting started](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/getting_started.html) episode of the lesson.

**Comment by dyaramatreya** [comment]
hi @mkuzak 
Can I take this issue up?

**Comment by mkuzak** [comment]
Hi @dyaramatreya  thank you for the offer :). I appreciate it. This repository was created to teach the workshop at the [Open Science Festival](https://opensciencefestival.nl/). The issues in this repository are only meant to be fixed during the workshop by in-person participants.

**Comment by dyaramatreya** [comment]
Ok. So the PR won't be merged? Or will it be merged during the workshop?

**Comment by mkuzak** [comment]
It won't. During the workshop, we will ask participants to make PRs which fix those issues.
I closed your PR. Sorry about that.

**Comment by slingerbv** [comment]
Good job @OSCEindhoven
