### ISSUE TITLE
Rephrase one of the keypoints in functions episode

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#17]
Change `and **how** to do it (_implementation_)` to `and **how** will it do it (_implementation_)`. The phrase is located at the bottom of the [episodes/functions.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/functions.Rmd) on [line 148](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/functions.Rmd#L148C95-L148C95).

See the [Functions episode](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/functions.html) of the lesson.

**Comment by ColetteBos** [comment]
I will fix it. Maybe changing to "and **how** we want to do it (_implementation_)" is better?
