### ISSUE TITLE
The word `University` in the licenses episode should be lower case.

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#18]
Correct `University` to `university` in the Licenses episode, file [episodes/licenses.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/licenses.Rmd) on [line 32](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/licenses.Rmd#L32C41-L32C51).

See the [Licenses episode](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/licenses.html) of the lesson.

**Comment by nrvanulzen** [comment]
Niek is going to fix this
