### ISSUE TITLE
Rephrase one of the lesson objectives in Testing episode

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#19]
Rephrase one of the lesson objectives, `Learn to not panic if a test fails` to `Learn how not to panic when a test fails`. The objective is located on [line 15](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/testing.Rmd#L15C3-L15C37) of the [episodes/testing.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/testing.Rmd).

See the [Testing episode](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/testing.html) of the lesson.

**Comment by dirkvangorp** [comment]
@mkuzak I will solve this issue
