### ISSUE TITLE
Rephrase the keypoint in Managing dependencies episode.

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#20]
In the Managing dependencies episode, rephrase the keypoint to improve grammar. Change `The `DESCRIPTION` file helps us keeping track of our package's dependencies` to `The `DESCRIPTION` file helps us keep track of our package's dependencies.` The keypoint is located a the bottom of the [episodes/dependencies.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/dependencies.Rmd) on [line 158](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/dependencies.Rmd#L158C3-L158C78).

See the [Dependencies episode](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/dependencies.html) of the lesson.

**Comment by asoaresca** [comment]
@mkuzak I will fix this!
