### ISSUE TITLE
Fix typo in Vignettes episode

### ISSUE THREAD

**Issue by mkuzak** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#24]
In [episodes/vignettes.Rmd](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/episodes/vignettes.Rmd) on [line 223](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/a881b8b021f30d60712a1ae468c0b5b1cc2c5408/episodes/vignettes.Rmd#L223) it states `When yoy choose` it should be `When you choose`.

See [The Vignettes page](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/vignettes.html) of the lesson.

**Comment by ASarafoglou** [comment]
I will be fixing this typo!

**Comment by YaraToenders** [comment]
I will fix this
