### ISSUE TITLE
The link to Rstudio is not working in setup

### ISSUE THREAD

**Issue by liekelotte** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#8]
When clicking the link to Rstudio on the [setup page](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/#required-software), there is an error. I believe the [setup file](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/learners/setup.md) needs to be correctd for it to work

**Comment by ElenaMartens** [comment]
I am picking it up

**Comment by Royashokoohi** [comment]
Thank you
