### ISSUE TITLE
Mziki Johnson' learner profile can be improved

### ISSUE THREAD

**Issue by liekelotte** [researchsoftwaretrainingNL/OSF-Rpackaging-lesson#9]
I believe [Mziki Johnson's learner profile](https://researchsoftwaretrainingnl.github.io/OSF-Rpackaging-lesson/profiles.html) includes some grammatical mistakes and maybe too limited information about their motivation for learning R packaging. We should update the [learner profile file](https://github.com/researchsoftwaretrainingNL/OSF-Rpackaging-lesson/blob/main/profiles/learner-profiles.md).

**Comment by MpaulaL** [comment]
Hi Stephanie and Dan! I will pick up this issue.

**Comment by MpaulaL** [comment]
Solved by #27
